---
server_memory_size: 5048mb
env: st

common_env_files:
  - filepath: "files/st/keys/"
    filename: "agf_out_keyStore.p12"
    dest: "/tmp"
  - filepath: "files/st/keys/"
    filename: "agf_in_trustStore.p12"
    dest: "/tmp"
  - filepath: "files/st/keys/"
    filename: "agf_out_trustStore.p12"
    dest: "/tmp"
  - filepath: "files/st/A"
    filename: "GB_USER.txt"
    dest: "/tmp"
  - filepath: "files/st/"
    filename: "databaseConfig.xml"
    dest: "/tmp"
  - filepath: "files/st/"
    filename: "sslConfig.xml"
    dest: "/tmp"

specific_st01_files:
  - filepath: "files/st/keys/"
    filename: "agf_in_keyStore_st01.txt"
    dest: "/tmp"
  - filepath: "files/st/st01/"
    filename: "jvm.options"
    dest: "/tmp"
  - filepath: "files/st/st01/"
    filename: "iiq_files.txt"
    dest: "/tmp"
  - filepath: "files/st/st01/"
    filename: "iiq_values.txt"
    dest: "/tmp"
  - filepath: "files/st/st01/"
    filename: "bootstrap.properties"
    dest: "/tmp"
